// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_optin from "./routes/api/optin.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $CategoryTabs from "./islands/CategoryTabs.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_ModalLoginCustom from "./islands/Header/ModalLoginCustom.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $ImageZoom from "./islands/ImageZoom.tsx";
import * as $MiniCart from "./islands/MiniCart.tsx";
import * as $NJYouTubeModal from "./islands/NJYouTubeModal.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $NewsletterFooter from "./islands/NewsletterFooter.tsx";
import * as $NewsletterModal from "./islands/NewsletterModal.tsx";
import * as $NickJonas_NJLPCarousel from "./islands/NickJonas/NJLPCarousel.tsx";
import * as $NickJonas_NJProductCarousel from "./islands/NickJonas/NJProductCarousel.tsx";
import * as $NickJonas_NJSimpleCarousel from "./islands/NickJonas/NJSimpleCarousel.tsx";
import * as $NickJonas_ScrollTriggeredCarousel from "./islands/NickJonas/ScrollTriggeredCarousel.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $Pagination from "./islands/Pagination.tsx";
import * as $Partner_Insider_UserObject from "./islands/Partner/Insider/UserObject.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductSliderDotsHandler from "./islands/ProductSliderDotsHandler.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $ShowMore from "./islands/ShowMore.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $UTMSaveController from "./islands/UTMSaveController.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import * as $YourQA from "./islands/YourQA.tsx";
import * as $YourReviews from "./islands/YourReviews.tsx";
import * as $Zendesk from "./islands/Zendesk.tsx";
import * as $christmas_HeroCarousel from "./islands/christmas/HeroCarousel.tsx";
import * as $christmas_ProductCarousel from "./islands/christmas/ProductCarousel.tsx";
import * as $christmas_carousel_CarouselContainer from "./islands/christmas/carousel/CarouselContainer.tsx";
import * as $christmas_carousel_CarouselSlide from "./islands/christmas/carousel/CarouselSlide.tsx";
import * as $christmas_carousel_GoldFrame from "./islands/christmas/carousel/GoldFrame.tsx";
import * as $christmas_carousel_constants from "./islands/christmas/carousel/constants.ts";
import * as $christmas_carousel_useCarouselLogic from "./islands/christmas/carousel/useCarouselLogic.ts";
import * as $sort from "./islands/sort.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/optin.tsx": $api_optin,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/CategoryTabs.tsx": $CategoryTabs,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/ModalLoginCustom.tsx": $Header_ModalLoginCustom,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/ImageZoom.tsx": $ImageZoom,
    "./islands/MiniCart.tsx": $MiniCart,
    "./islands/NJYouTubeModal.tsx": $NJYouTubeModal,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/NewsletterFooter.tsx": $NewsletterFooter,
    "./islands/NewsletterModal.tsx": $NewsletterModal,
    "./islands/NickJonas/NJLPCarousel.tsx": $NickJonas_NJLPCarousel,
    "./islands/NickJonas/NJProductCarousel.tsx": $NickJonas_NJProductCarousel,
    "./islands/NickJonas/NJSimpleCarousel.tsx": $NickJonas_NJSimpleCarousel,
    "./islands/NickJonas/ScrollTriggeredCarousel.tsx":
      $NickJonas_ScrollTriggeredCarousel,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/Pagination.tsx": $Pagination,
    "./islands/Partner/Insider/UserObject.tsx": $Partner_Insider_UserObject,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductSliderDotsHandler.tsx": $ProductSliderDotsHandler,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/ShowMore.tsx": $ShowMore,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/UTMSaveController.tsx": $UTMSaveController,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
    "./islands/YourQA.tsx": $YourQA,
    "./islands/YourReviews.tsx": $YourReviews,
    "./islands/Zendesk.tsx": $Zendesk,
    "./islands/christmas/HeroCarousel.tsx": $christmas_HeroCarousel,
    "./islands/christmas/ProductCarousel.tsx": $christmas_ProductCarousel,
    "./islands/christmas/carousel/CarouselContainer.tsx":
      $christmas_carousel_CarouselContainer,
    "./islands/christmas/carousel/CarouselSlide.tsx":
      $christmas_carousel_CarouselSlide,
    "./islands/christmas/carousel/GoldFrame.tsx": $christmas_carousel_GoldFrame,
    "./islands/christmas/carousel/constants.ts": $christmas_carousel_constants,
    "./islands/christmas/carousel/useCarouselLogic.ts":
      $christmas_carousel_useCarouselLogic,
    "./islands/sort.tsx": $sort,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
